"""add featured field in Pizza

Revision ID: 11e0922fbfcb
Revises: f8dbdc3eb681
Create Date: 2025-09-25 00:15:00.441748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11e0922fbfcb"
down_revision: Union[str, Sequence[str], None] = "f8dbdc3eb681"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pizza",
        sa.Column("featured", sa.Boolean(), nullable=False, server_default="FALSE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pizza", "featured")
    # ### end Alembic commands ###
