"""change currency related fields from float to decimal

Revision ID: 1a88bd5f636b
Revises: 11e0922fbfcb
Create Date: 2025-10-03 19:18:42.457643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a88bd5f636b'
down_revision: Union[str, Sequence[str], None] = '11e0922fbfcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('cart', 'tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('cart', 'delivery_charge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('cart', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('cart_item', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_item', 'total',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('cart', 'total',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('cart', 'delivery_charge',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('cart', 'tax',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('cart', 'subtotal',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
