"""add unique default address per user constraint

Revision ID: 276cb9e851a0
Revises: 5156149ad8f1
Create Date: 2025-10-15 22:18:35.796031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276cb9e851a0'
down_revision: Union[str, Sequence[str], None] = '5156149ad8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_default_address_per_user', 'addresses', ['user_id'], unique=True, postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_default_address_per_user', table_name='addresses', postgresql_where=sa.text('is_default = true'))
    # ### end Alembic commands ###
