"""change on-delete to set-null in address-field on order model

Revision ID: 2a10cf9c9dd9
Revises: ea5f74139c0a
Create Date: 2025-10-24 22:18:08.135300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a10cf9c9dd9"
down_revision: Union[str, Sequence[str], None] = "ea5f74139c0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "address_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        "fk_orders_address_id",
        "orders",
        "addresses",
        ["address_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_orders_address_id", "orders", type_="foreignkey")
    op.alter_column("orders", "address_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
