"""cart and cart_item models

Revision ID: f8dbdc3eb681
Revises: 260e0c745508
Create Date: 2025-09-07 14:45:59.766912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8dbdc3eb681'
down_revision: Union[str, Sequence[str], None] = '260e0c745508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('delivery_charge', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('pizza_id', sa.Uuid(), nullable=False),
    sa.Column('size_id', sa.Uuid(), nullable=False),
    sa.Column('crust_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['crust_id'], ['crust.id'], ),
    sa.ForeignKeyConstraint(['pizza_id'], ['pizza.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_item_topping',
    sa.Column('cart_item_id', sa.Uuid(), nullable=False),
    sa.Column('topping_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_item.id'], ),
    sa.ForeignKeyConstraint(['topping_id'], ['topping.id'], ),
    sa.PrimaryKeyConstraint('cart_item_id', 'topping_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item_topping')
    op.drop_table('cart_item')
    op.drop_table('cart')
    # ### end Alembic commands ###
